version: '3' 
services:
  uml-designer-docker:
    image: openkbs/uml-designer-docker
    build:
      context: .
      dockerfile: Dockerfile
    container_name: uml-designer-docker
    environment:
      - USER_ID=${USER_ID:-1000}
      - GROUP_ID=${GROUP_ID:-1000}
      - DISPLAY=${DISPLAY:-":0.0"}
    env_file:
      - ./docker.env
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
      - ./workspace:/home/developer/workspace
      - ./.metadata:/home/developer/.metadata
      - ./.eclipse:/home/developer/.eclipse

